# Generated by Django 3.1.7 on 2021-05-31 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_auto_20210530_2132'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=38)),
                ('description', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('A0', 'Asamblea'), ('A1', 'Admisión de Aspirantes'), ('C0', 'Cumpleaños'), ('C1', 'Charla'), ('C2', 'Conferencia'), ('C3', 'Convenio'), ('N0', 'Novatada'), ('P0', 'Proyecto'), ('R0', 'Reunión')], max_length=2)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('observations', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(blank=True, default='NO LINK', null=True)),
                ('participants', models.JSONField(default=dict)),
                ('gallery', models.JSONField(blank=True, default=dict, null=True)),
                ('id_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
                ('id_suborg_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.suborganization')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('C1', 'Carta'), ('C2', 'Constitución'), ('C3', 'Convenio'), ('E0', 'Evidenia de reunión'), ('P0', 'Propuesta de proyecto'), ('S0', 'Solicitud')], max_length=2)),
                ('link', models.URLField(blank=True, default='NO LINK', null=True)),
                ('id_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('id_writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
