# Generated by Django 4.1.3 on 2022-11-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220106_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
