# Generated by Django 3.1.7 on 2021-05-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_doc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.JSONField(default=dict),
        ),
    ]
