# Generated by Django 3.1.7 on 2021-05-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
