# Generated by Django 3.1.7 on 2021-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('C1', 'Carta'), ('C2', 'Constitución'), ('C3', 'Convenio'), ('E0', 'Evidenia de reunión'), ('P0', 'Propuesta de proyecto'), ('S0', 'Solicitud')], max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('A0', 'Asamblea'), ('A1', 'Admisión de Aspirantes'), ('C0', 'Cumpleaños'), ('C1', 'Charla'), ('C2', 'Conferencia'), ('C3', 'Convenio'), ('N0', 'Novatada'), ('P0', 'Proyecto'), ('R0', 'Reunión')], max_length=2),
        ),
    ]
