# Generated by Django 3.1.7 on 2021-05-31 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suborganization',
            name='id_member_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suborganization',
            name='id_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.organization'),
        ),
        migrations.AddField(
            model_name='suborganization',
            name='members',
            field=models.ManyToManyField(related_name='list_of_branch_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='id_tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
        migrations.AddField(
            model_name='career',
            name='id_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.faculty'),
        ),
    ]
