# Generated by Django 3.1.7 on 2021-05-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210415_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
