# Generated by Django 3.1.7 on 2021-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210507_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='gallery',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='mission',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='suborganization',
            name='gallery',
            field=models.JSONField(default=dict),
        ),
    ]
