# Generated by Django 3.1.7 on 2021-05-12 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0005_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganization',
            name='id_member_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suborganization',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
