# Generated by Django 4.1.3 on 2022-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_alter_suborganization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganization',
            name='gallery',
            field=models.JSONField(default=dict, help_text='La pagina para convertir a (x)html es :https://greywyvern.com/code/php/binary2base64\nY el formato de cada elemento es {"src":"data arrojada por la pagina"}'),
        ),
    ]
