# Generated by Django 3.1.7 on 2021-06-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.person'),
        ),
    ]
