# Generated by Django 3.1.7 on 2022-09-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_member',
        ),
        migrations.AddField(
            model_name='member',
            name='id_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
