# Generated by Django 4.1.3 on 2022-11-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220915_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
