# Generated by Django 3.1.7 on 2021-04-23 22:29

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_table_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ambassador',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True, validators=[user.validators.ambassador_valid_url]),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
