# Generated by Django 3.1.7 on 2021-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_member_nulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='name',
            field=models.CharField(choices=[('P', 'Presidente'), ('V', 'Vicepresidente'), ('S', 'Secretario'), ('T', 'Tesorero'), ('V', 'Vocal'), ('M', 'Miembro'), ('N', 'Ninguno'), ('A', 'Asesor'), ('T', 'Tutor'), ('E', 'Externo')], default='M', max_length=2),
        ),
    ]
