# Generated by Django 3.1.7 on 2021-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='permissions',
            field=models.CharField(choices=[('A', 'Presidente'), ('B', 'Vicepresidente'), ('C', 'Sub Organización'), ('D', 'Miembro'), ('N', 'Ninguno')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='name',
            field=models.CharField(choices=[('P', 'Presidente'), ('V', 'Vicepresidente'), ('S', 'Secretario'), ('T', 'Tesorero'), ('V', 'Vocal'), ('M', 'Miembro'), ('N', 'Ninguno'), ('A', 'Asesor'), ('T', 'Tutor'), ('E', 'Externo'), ('C', 'Candidato Aspirante')], default='M', max_length=1),
        ),
    ]
