# Generated by Django 3.1.7 on 2021-05-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_choices_jsonfield_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
