# Generated by Django 3.1.7 on 2021-05-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_suborg_dep'),
        ('user', '0010_desc_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.career'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.faculty'),
        ),
    ]
