# Generated by Django 3.1.7 on 2021-05-13 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210512_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='actual_role',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_student',
        ),
        migrations.AddField(
            model_name='person',
            name='actual_role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.memberrole'),
        ),
        migrations.AddField(
            model_name='professor',
            name='id_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='id_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
