# Generated by Django 3.1.7 on 2021-05-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210519_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('101', '100-I'), ('102', '100-II'), ('201', '200-I'), ('202', '200-II'), ('301', '300-I'), ('302', '300-II'), ('401', '400-I'), ('402', '400-II')], max_length=6),
        ),
    ]
