# Generated by Django 3.1.7 on 2021-05-31 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210530_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_sub_org',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id_member',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id_person',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_person',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='professor',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=123, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='person',
            name='actual_role',
            field=models.CharField(choices=[('P', 'Presidente'), ('V', 'Vicepresidente'), ('S', 'Secretario'), ('T', 'Tesorero'), ('V', 'Vocal'), ('M', 'Miembro'), ('N', 'Ninguno'), ('A', 'Asesor'), ('T', 'Tutor'), ('E', 'Externo'), ('C', 'Candidato Aspirante')], default='N', max_length=1),
        ),
    ]
